# Generated by Django 6.0.7 on 2026-07-17 15:54

from django.db import migrations
from phonenumber_field.phonenumber import to_python

def normalize_owner_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    
    flats = Flat.objects.all()
    
    for flat in flats.iterator():
        if flat.owners_phonenumber:
            phone_object = to_python(flat.owners_phonenumber)
            
            if phone_object and phone_object.is_valid():
                flat.owner_pure_phone = phone_object
                flat.save(update_fields=['owner_pure_phone'])
            else:
                print(f"Не удалось распознать номер для ID {flat.id}: {flat.owners_phonenumber}")

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_owner_phones, move_backward),
    ]
