# Generated by Django 6.0.7 on 2026-07-19 08:55

from django.db import migrations


def transfer_owners_data(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    unique_flat_owners = Flat.objects.values_list(
        "owner", "owners_phonenumber", "owner_pure_phone"
    ).distinct()

    owners_to_create = []
    for owner_name, phone, pure_phone in unique_flat_owners:
        owners_to_create.append(
            Owner(
                owner=owner_name,
                owners_phonenumber=phone,
                owner_pure_phone=pure_phone,
            )
        )

    Owner.objects.bulk_create(owners_to_create, ignore_conflicts=True)

    owner_cache = {
        (o.owner, o.owners_phonenumber): o.id
        for o in Owner.objects.only("id", "owner", "owners_phonenumber")
    }

    FlatOwnerRelation = Owner.flats.through
    relations_to_create = []

    for flat in Flat.objects.only(
        "id", "owner", "owners_phonenumber"
    ).iterator():
        owner_id = owner_cache.get((flat.owner, flat.owners_phonenumber))
        if owner_id:
            relations_to_create.append(
                FlatOwnerRelation(owner_id=owner_id, flat_id=flat.id)
            )

    FlatOwnerRelation.objects.bulk_create(
        relations_to_create, batch_size=5000, ignore_conflicts=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_owner"),
    ]

    operations = [
        migrations.RunPython(transfer_owners_data),
    ]
